
package com.alvarobajo.views.panel;

import com.alvarobajo.Controllers.DAOVentasImpl;
import com.alvarobajo.interfaces.DAOVentas;
import com.alvarobajo.models.Clientes;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alvaroBajo
 */
public class PorClientes extends javax.swing.JPanel {
    
    int idCliente = 0;

    /**
     * Creates new form Porfechas
     */
    public PorClientes() {
        initComponents();
        cargarClientes();
        initStyles();
    }
    
    private void initStyles(){
       txtTitulo.putClientProperty( "FlatLaf.styleClass", "h00" ); 
       txtLeyenda.putClientProperty( "FlatLaf.styleClass", "h2" );
       txtCliente.putClientProperty( "FlatLaf.styleClass", "h4" );
       txtBuscarCliente.putClientProperty( "FlatLaf.styleClass", "h4" );
       comBuscarCliente.putClientProperty( "FlatLaf.styleClass", "h4" );
       jButtonBuscar.putClientProperty( "FlatLaf.styleClass", "h00" );
       
    }

    
    
    
    
    private void cargarClientes() {

        try {
            DAOVentas dao = new DAOVentasImpl();
            ArrayList<Clientes> lista = (ArrayList<Clientes>) dao.listar("");
            comBuscarCliente.removeAllItems();
            comBuscarCliente.addItem("selecione cliente");
            for (int i = 0; i < lista.size(); i++) {
                comBuscarCliente.addItem(lista.get(i).getNombre());
            }
        } catch (Exception ex) {
            System.out.println("error:" + ex);
        }
    }
    
    
    private void botonBuscar() {
        try {
            String colum = txtBuscarCliente.getText();
            DAOVentas dao = new DAOVentasImpl();
            ArrayList<Clientes> lista = (ArrayList<Clientes>) dao.listar(colum);
            comBuscarCliente.removeAllItems();
            if (!lista.isEmpty()) {
                for (int i = 0; i < lista.size(); i++) {
                    comBuscarCliente.addItem(lista.get(i).getNombre());
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe cliente con ese numero", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                txtBuscarCliente.requestFocus();
                cargarClientes();
                comBuscarCliente.setSelectedItem("selecione cliente");
            }
            txtBuscarCliente.setText("");
        } catch (Exception ex) {
            System.out.println("!ERROR¡" + ex);
        }
    }
    
    private void generarPdf(){
        DAOVentas dao = new DAOVentasImpl();
        String nombres = comBuscarCliente.getSelectedItem().toString().trim();
        try {
            dao.clienteVentas(nombres);
        } catch (Exception ex) {
            Logger.getLogger(PorClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        jButtonPDF = new javax.swing.JButton();
        comBuscarCliente = new javax.swing.JComboBox<>();
        txtCliente = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        txtLeyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1374, 748));
        setMinimumSize(new java.awt.Dimension(1374, 748));

        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Selecione Cliente");

        jButtonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alvarobajo/img/icons8-pdf-2-48.png"))); // NOI18N
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });

        comBuscarCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione cliente" }));

        txtCliente.setText("Cliente:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        txtLeyenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLeyenda.setText("Aquí podrá generar un PDF con las compras de un cliente, en el cual le mostrara todas las compas registradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(540, 540, 540)
                                .addComponent(jButtonPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(comBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(221, 221, 221)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLeyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(txtLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButtonPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        botonBuscar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        if (!comBuscarCliente.getSelectedItem().equals("selecione cliente")){
            generarPdf();
        }else{
            JOptionPane.showMessageDialog(this, "debe selecionar un cliente \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comBuscarCliente;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtLeyenda;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
