
package com.alvarobajo.views.panel;

import com.alvarobajo.Controllers.DAOVentasImpl;
import com.alvarobajo.interfaces.DAOVentas;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author alvaroBajo
 */
public class Porfechas extends javax.swing.JPanel {

    public static String fecha_inicio;
    public static String fecha_fin;

    /**
     * Creates new form Porfechas
     */
    public Porfechas() {
        initComponents();
        initStyles();
    }
    private void initStyles(){
       txtTitulo.putClientProperty( "FlatLaf.styleClass", "h00" ); 
       txtLeyenda.putClientProperty( "FlatLaf.styleClass", "h2" );
       txtFechaI.putClientProperty( "FlatLaf.styleClass", "h4" );
       txtFechaF.putClientProperty( "FlatLaf.styleClass", "h4" );
    }
    private void crearPdf() {
        DAOVentas venta = new DAOVentasImpl();
        try {
            venta.ventasPorFecha();
        } catch (Exception ex) {
            Logger.getLogger(Porfechas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        txtFechaI = new javax.swing.JLabel();
        txtFechaF = new javax.swing.JLabel();
        jDFechaInicio = new com.toedter.calendar.JDateChooser();
        jDFechaFin = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtLeyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1374, 748));
        setMinimumSize(new java.awt.Dimension(1374, 748));

        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Selecione el rango de fechas");

        txtFechaI.setText("Fecha de inicio:");

        txtFechaF.setText("Fecha de fin:");

        jDFechaInicio.setDateFormatString("yyyy-MM-dd");

        jDFechaFin.setDateFormatString("yyyy-MM-dd");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alvarobajo/img/icons8-pdf-2-48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtLeyenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLeyenda.setText("Aquí podrá generar un PDF con un rango de fechas, en el cual le mostrara todas las compas registradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 389, Short.MAX_VALUE))
                    .addComponent(txtLeyenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jDFechaInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe selecionar fecha de inicio", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else if (jDFechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe selecionar fecha Fin", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            fecha_fin = ((JTextField) jDFechaFin.getDateEditor().getUiComponent()).getText();
            fecha_inicio = ((JTextField) jDFechaInicio.getDateEditor().getUiComponent()).getText();
            crearPdf();
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDFechaFin;
    private com.toedter.calendar.JDateChooser jDFechaInicio;
    private javax.swing.JLabel txtFechaF;
    private javax.swing.JLabel txtFechaI;
    private javax.swing.JLabel txtLeyenda;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
